apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: la-blue
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: la-app
        version: 1.0.0
    spec:
      containers:
        - name: la-blue
          image: linuxacademycontent/content-gcp-labs:deploy-blue
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              memory: 100Mi
