kind: Service
apiVersion: v1
metadata:
  name: la-service
spec:
  type: LoadBalancer
  selector:
    app: la-app
    version: 2.0.0
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
